repos:
-   repo: local
    hooks:
    -   id: build_date
        name: build_date
        entry: bash -c 'now=\"$(date -Im)\"; for file in "${@}"; do sed -i "s/process.env.BUILD_DATE/$now/" "$file"; done'
        language: system
        pass_filenames: true
        files: ^static/js/build/
