
# File to run a "dev" environment locally
services:
  db:
    image: postgres-crypto:14
    build:
      context: .
      dockerfile: docker-postgres.Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker_volumes/postgresql/data:/var/lib/postgresql/data
      - ./docker_volumes/dump_pgsql:/var/dump_pgsql
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./init.sql:/init-db.sql
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: rootdb
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256 --auth-host=scram-sha-256 --auth-local=scram-sha-256
      POSTGRES_API_USER: memuser
      POSTGRES_API_PASSWORD: mempass
      POSTGRES_API_DB: memdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=memdb --username=memuser --timeout=5"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: memlike-api:3.12
    build:
      context: .
      dockerfile: docker-api.Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://memuser:mempass@db:5432/memdb
      MEMCACHIER_SERVERS: 127.0.0.1:11213
      MEMCACHIER_USERNAME: myuser
      MEMCACHIER_PASSWORD: mypass
      POSTGRES_USER: memuser
      POSTGRES_PASSWORD: mempass
      POSTGRES_DB: memdb
      DEBUG: 1
      DEBUG_SQL: 1
      AUTORELOAD: 1
      PYTHONUNBUFFERED: 1
      SESSION_BACKEND: session.CookieDataStore
    platform: linux/amd64
    volumes:
      - .:/srv
      - api_logs:/var/logs
      - api_sessions:/tmp/sessions
    healthcheck:
      disable: true
    command: >
      python -u src/app-entrypoint.py

volumes:
  api_logs:
  api_sessions:
