version: '3'

# File to run a "dev" environment locally
services:
  db:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - ./docker_volumes/postgresql/data:/var/lib/postgresql/data
      - ./docker_volumes/dump_pgsql:/var/dump_pgsql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: memuser
      POSTGRES_PASSWORD: mempass
      POSTGRES_DB: memdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: memlike_api:latest
    build:
      context: .
      dockerfile: docker-api.Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://memuser:mempass@db:5432/memdb"
      MEMCACHIER_PASSWORD: ""
      MEMCACHIER_SERVERS: ""
      MEMCACHIER_USERNAME: ""
      POSTGRES_USER: memuser
      POSTGRES_PASSWORD: mempass
      POSTGRES_DB: memdb
      DEBUG: 1
    platform: linux/amd64
    volumes:
      - ./clearmemcached.sh:/srv/clearmemcached.sh
      - ./src:/srv/src:delegated
      - ./static:/srv/static:delegated
    healthcheck:
      disable: true
    command: >
      python src/app-entrypoint.py