[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Memlike"
dynamic = ["version"]
requires-python = ">= 3.12"
authors = [
  {name = "Anon Software Foundation", email = "foundation@anon.com"},
]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"

# Ruleset for ruff check
# You can override it using CLI args: ruff check --select F401
# https://moritzguck.github.io/Code-Cheatsheets/cheatsheets/Languages/Python/ruff.html
[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E203", "E402"]

# Ruleset for ruff format --check
# formats your code according to black's style guide
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = false
