[tox]
requires =
    tox >= 3
envlist =
    py{312}
# Enable the tox - pip - deps - upgrade plugin
addopts = --pip - deps - upgrade
isolated_build = True

[pkgenv]
pass_env =
    SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYTEST

[testenv]
deps =
    -r /srv/requirements.txt
setenv =
    # See https://docs.python.org/3/library/io.html#io-encoding-warning
    # If we don't enable this, neither can any of our downstream users!
    # pylib is not PYTHONWARNDEFAULTENCODING clean, so don't set for it.
    !pylib: PYTHONWARNDEFAULTENCODING=

[testenv:test]
# skip_install so that we wont create a memlike.tar.gz package and install it (can't use "import memlike")
skip_install = true
changedir = src
commands = python -m pytest tests -s -x
deps =
    -r /srv/requirements.txt
    pytest
setenv =
    PYTHONDONTWRITEBYTECODE=1
    MEMRISE_ANON_USERNAME=
    MEMRISE_ANON_PASSWORD=
    DATABASE_URL=postgres://memuser:mempass@db:5432/memdb_test
pass_env =
    MEMCACHIER_SERVERS
    MEMCACHIER_USERNAME
    MEMCACHIER_PASSWORD

[testenv:flake8]
usedevelop = false
deps =
    flake8 >= 5.0
commands =
    flake8 src

[testenv:linting]
commands = pre-commit run --all-files --show-diff-on-failure {posargs:}
deps =
    pre-commit >= 2.9.3
setenv =
    # pre-commit and tools it launches are not clean of this warning.
    PYTHONWARNDEFAULTENCODING=

[flake8]
extend-ignore = E202,E203,E402
exclude = .git,__pycache__,.tox,.tox4,.pytest_cache,static/js
max-complexity = 10
max-line-length = 120
