# coding=utf-8
MENU = [
    {"slug": "index", "url": "/"},
    {"slug": "courses", "url": "/community/courses/"},
    {"slug": "login", "url": "/login"},
]

LOCALES = [
    {"slug": "english", "name": "English", "photo": "/static/img/flag_uk.svg"},
    {"slug": "french", "name": "Français", "photo": "/static/img/flag_french.svg"},
]

# https://static.memrise.com/uploads/language_photos/german.png
languages = {
    "afrikaans": {"photo_url": "/static/img/language_photos/Afrikaans.png"},
    "albanian": {"photo_url": "/static/img/language_photos/albanian.png"},
    "american-sign-language-asl": {"photo_url": "/static/img/language_photos/sign-american.png"},
    "ancient-greek": {"photo_url": "/static/img/language_photos/Ancient-Greek.png"},
    "arabic": {"photo_url": "/static/img/language_photos/arabic.png"},
    "armenian": {"photo_url": "/static/img/language_photos/armenian.png"},
    "azerbaijani": {"photo_url": "/static/img/language_photos/azerbaijini.png"},
    "basque": {"photo_url": "/static/img/language_photos/DemoFlags-38_copy.png"},
    "belarusian": {"photo_url": "/static/img/language_photos/belarus.png"},
    "bengali": {"photo_url": "/static/img/language_photos/DemoFlags-61_copy.png"},
    "bosnian": {"photo_url": "/static/img/language_photos/DemoFlags-71_copy.png"},
    "bulgarian": {"photo_url": "/static/img/language_photos/DemoFlags-66_copy.png"},
    "burmese": {"photo_url": "/static/img/language_photos/burmese.png"},
    "cantonese": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "cantonese-jyutping": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "catalan": {"photo_url": "/static/img/language_photos/DemoFlags-29_copy.png"},
    "chinese-simplified": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "chinese-traditional": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "croatian": {"photo_url": "/static/img/language_photos/DemoFlags-30_copy.png"},
    "czech": {"photo_url": "/static/img/language_photos/DemoFlags-19_copy.png"},
    "danish": {"photo_url": "/static/img/language_photos/DemoFlags-25_copy.png"},
    "dutch": {"photo_url": "/static/img/language_photos/Flags_Dutch_copy.png"},
    "english": {"photo_url": "/static/img/language_photos/en.png"},
    "english-us": {"photo_url": "/static/img/language_photos/us_flag.png"},
    "esperanto": {"photo_url": "/static/img/language_photos/DemoFlags-34_copy.png"},
    "estonian": {"photo_url": "/static/img/language_photos/DemoFlags-32_copy.png"},
    "faroese": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Faroese.png"},
    "finnish": {"photo_url": "/static/img/language_photos/DemoFlags-22_copy.png"},
    "flemish": {"photo_url": "/static/img/language_photos/flemish.png"},
    "french": {"photo_url": "/static/img/language_photos/DemoFlags-02_copy.png"},
    "french-sign-language-lsf": {"photo_url": "/static/img/language_photos/sign-french.png"},
    "galician": {"photo_url": "/static/img/language_photos/galician-flag.png"},
    "georgian": {"photo_url": "/static/img/language_photos/georgian.png"},
    "german": {"photo_url": "/static/img/language_photos/german.png"},
    "greek": {"photo_url": "/static/img/language_photos/DemoFlags-26_copy.png"},
    "greenlandic": {"photo_url": "/static/img/language_photos/greenland.png"},
    "hakka": {"photo_url": "/static/img/language_photos/hakka.png"},
    "hebrew": {"photo_url": "/static/img/language_photos/DemoFlags-24_copy.png"},
    "hindi": {"photo_url": "/static/img/language_photos/DemoFlags-28_copy.png"},
    "hungarian": {"photo_url": "/static/img/language_photos/DemoFlags-21_copy.png"},
    "icelandic": {"photo_url": "/static/img/language_photos/DemoFlags-35_copy.png"},
    "indonesian": {"photo_url": "/static/img/language_photos/DemoFlags-64_copy.png"},
    "irish": {"photo_url": "/static/img/language_photos/DemoFlags-12_copy.png"},
    "italian": {"photo_url": "/static/img/language_photos/DemoFlags-06_copy.png"},
    "japanese-4": {"photo_url": "/static/img/language_photos/DemoFlags-09_copy.png"},
    "japanese-no-script": {"photo_url": "/static/img/language_photos/DemoFlags-09_copy.png"},
    "kanji": {"photo_url": "/static/img/language_photos/DemoFlags-09_copy.png"},
    "kazakh": {"photo_url": "/static/img/language_photos/DemoFlags-62_copy.png"},
    "khmer": {"photo_url": "/static/img/language_photos/khmer.png"},
    "korean": {"photo_url": "/static/img/language_photos/korean-flag.png"},
    "kurdish": {"photo_url": "/static/img/language_photos/kurdish-flag1.png"},
    "kyrgyz": {"photo_url": "/static/img/language_photos/kyrgyz.png"},
    "ladin": {"photo_url": "/static/img/language_photos/ladin.png"},
    "latin": {"photo_url": "/static/img/language_photos/latin.png"},
    "latvian": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Latvian.png"},
    "lithuanian": {"photo_url": "/static/img/language_photos/DemoFlags-37_copy.png"},
    "luxembourgish": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Luxembourgish.png"},
    "macedonian": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Macedonian.png"},
    "malay": {"photo_url": "/static/img/language_photos/DemoFlags-60_copy.png"},
    "malayalam": {},
    "maltese": {"photo_url": "/static/img/language_photos/maltese-flag1.png"},
    "mandarin-spoken-only": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "maori": {"photo_url": "/static/img/language_photos/DemoFlags-55_copy.png"},
    "marathi": {"photo_url": "/static/img/language_photos/DemoFlags-41_copy.png"},
    "mongolian": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Mongolian.png"},
    "nepali": {"photo_url": "/static/img/language_photos/Nepalese.png"},
    "norwegian": {"photo_url": "/static/img/language_photos/DemoFlags-23_copy.png"},
    "occitan": {"photo_url": "/static/img/language_photos/occitan_flag.png"},
    "other-language": {"photo_url": "/static/img/language_photos/other-languages.png"},
    "persian": {"photo_url": "/static/img/language_photos/farsi.png"},
    "polish": {"photo_url": "/static/img/language_photos/DemoFlags-51_copy.png"},
    "portuguese-brazil": {"photo_url": "/static/img/language_photos/pt-br.png"},
    "portuguese-portugal-2": {"photo_url": "/static/img/language_photos/DemoFlags-31_copy.png"},
    "punjabi": {},
    "romanian": {"photo_url": "/static/img/language_photos/Romanian.png"},
    "russian": {"photo_url": "/static/img/language_photos/DemoFlags-20_copy.png"},
    "sanskrit": {"photo_url": "/static/img/language_photos/sanskrit.png"},
    "scots": {"photo_url": "/static/img/language_photos/DemoFlags-36_copy.png"},
    "serbian": {"photo_url": "/static/img/language_photos/DemoFlags-43_copy.png"},
    "slovak": {"photo_url": "/static/img/language_photos/DemoFlags-11_copy.png"},
    "slovenian": {"photo_url": "/static/img/language_photos/DemoFlags-16_copy.png"},
    "somali": {"photo_url": "/static/img/language_photos/somali.png"},
    "spanish-mexico": {"photo_url": "/static/img/language_photos/MEX.png"},
    "spanish-spain": {"photo_url": "/static/img/language_photos/DemoFlags-03_copy.png"},
    "swahili": {"photo_url": "/static/img/language_photos/DemoFlags-45_copy.png"},
    "swedish": {"photo_url": "/static/img/language_photos/DemoFlags-18_copy.png"},
    "tagalog": {"photo_url": "/static/img/language_photos/Tagalog.png"},
    "tamil": {"photo_url": "/static/img/language_photos/tamil-flag.v1.png"},
    "thai": {"photo_url": "/static/img/language_photos/DemoFlags-47_copy.png"},
    "turkish": {"photo_url": "/static/img/language_photos/DemoFlags-13_copy.png"},
    "ukrainian": {"photo_url": "/static/img/language_photos/DemoFlags-49_copy.png"},
    "urdu": {"photo_url": "/static/img/language_photos/urdu.png"},
    "vietnamese": {"photo_url": "/static/img/language_photos/vietnamese.png"},
    "welsh": {"photo_url": "/static/img/language_photos/Flags_Welsh_copy.png"},
    "zulu": {"photo_url": "/static/img/language_photos/Zulu.png"},
}

categories_tree = [
    {
        "id": "569",
        "code": "languages",
        "children": [
            {
                "id": "578",
                "code": "european",
                "children": [
                    {"id": "6", "code": "english"},
                    {"id": "964", "code": "spanish-mexico"},
                    {"id": "3", "code": "spanish-spain"},
                    {"id": "2", "code": "french"},
                    {
                        "id": "879",
                        "code": "german",
                        "children": [
                            {"id": "4", "code": "german-2"},
                            {"id": "842", "code": "small-german-dialects"},
                            {"id": "428", "code": "swiss-german"},
                        ],
                    },
                    {"id": "688", "code": "portuguese-brazil"},
                    {"id": "5", "code": "italian"},
                    {"id": "9", "code": "portuguese-portugal-2"},
                    {"id": "53", "code": "dutch"},
                    {"id": "19", "code": "finnish"},
                    {"id": "17", "code": "danish"},
                    {"id": "20", "code": "greek"},
                    {"id": "27", "code": "norwegian"},
                    {"id": "11", "code": "swedish"},
                    {"id": "67", "code": "albanian"},
                    {
                        "id": "79",
                        "code": "armenian",
                        "children": [
                            {"id": "926", "code": "eastern-armenian"},
                            {"id": "927", "code": "western-armenian"},
                        ],
                    },
                    {"id": "32", "code": "basque"},
                    {"id": "114", "code": "breton"},
                    {"id": "15", "code": "catalan"},
                    {"id": "139", "code": "cornish"},
                    {"id": "963", "code": "english-us"},
                    {"id": "18", "code": "estonian"},
                    {"id": "173", "code": "faroese"},
                    {"id": "767", "code": "flemish"},
                    {"id": "190", "code": "georgian"},
                    {"id": "950", "code": "gothic-2"},
                    {"id": "23", "code": "hungarian"},
                    {"id": "24", "code": "icelandic"},
                    {"id": "26", "code": "irish"},
                    {"id": "268", "code": "ladin"},
                    {"id": "269", "code": "ladino"},
                    {"id": "274", "code": "latvian"},
                    {"id": "35", "code": "lithuanian"},
                    {"id": "290", "code": "luxembourgish"},
                    {"id": "299", "code": "maltese"},
                    {"id": "305", "code": "manx"},
                    {"id": "353", "code": "occitan"},
                    {"id": "383", "code": "romanian"},
                    {
                        "id": "389",
                        "children": [
                            {"id": "286", "code": "lule-sami"},
                            {"id": "346", "code": "northern-sami"},
                            {"id": "421", "code": "southern-sami"},
                            {"id": "918", "code": "ume-sami"},
                        ],
                        "code": "sami-languages",
                    },
                    {"id": "39", "code": "scots"},
                    {"id": "183", "code": "scottish-gaelic"},
                    {"id": "40", "code": "welsh"},
                ],
            },
            {
                "id": "612",
                "code": "chinese",
                "children": [
                    {"id": "547", "code": "chinese-simplified"},
                    {"id": "550", "code": "chinese-traditional"},
                    {"id": "549", "code": "mandarin-spoken-only"},
                    {"id": "548", "code": "cantonese"},
                    {"id": "553", "code": "cantonese-jyutping"},
                    {"id": "552", "code": "ningbo-dialect"},
                    {"id": "551", "code": "taishanese"},
                    {"id": "919", "code": "hakka"},
                ],
            },
            {
                "id": "613",
                "code": "japanese",
                "children": [
                    {"id": "665", "code": "japanese-4"},
                    {"id": "666", "code": "kanji"},
                    {"id": "668", "code": "japanese-no-script"},
                ],
            },
            {
                "id": "582",
                "code": "indian",
                "children": [
                    {"id": "103", "code": "bengali"},
                    {"id": "201", "code": "gujarati"},
                    {"id": "22", "code": "hindi"},
                    {"id": "438", "code": "telugu"},
                    {"id": "470", "code": "urdu"},
                    {"id": "36", "code": "marathi"},
                    {"id": "240", "code": "kannada"},
                    {"id": "298", "code": "malayalam"},
                    {"id": "363", "code": "pali"},
                    {"id": "376", "code": "punjabi"},
                    {"id": "393", "code": "sanskrit"},
                    {"id": "434", "code": "tamang"},
                    {"id": "436", "code": "tamil"},
                ],
            },
            {
                "id": "614",
                "code": "asian-and-pacific",
                "children": [
                    {"id": "25", "code": "indonesian"},
                    {"id": "8", "code": "korean"},
                    {"id": "441", "code": "thai"},
                    {"id": "474", "code": "vietnamese"},
                    {"id": "322", "code": "mongolian"},
                    {"id": "42", "code": "azerbaijani"},
                    {"id": "49", "code": "hawaiian"},
                    {"id": "50", "code": "kazakh"},
                    {"id": "64", "code": "ainu"},
                    {"id": "965", "code": "australian"},
                    {"id": "117", "code": "burmese"},
                    {"id": "119", "code": "cebuano"},
                    {"id": "954", "code": "dzongkha-2"},
                    {"id": "955", "code": "javanese-2"},
                    {"id": "245", "code": "karen-languages"},
                    {"id": "122", "code": "khmer"},
                    {"id": "267", "code": "kyrgyz"},
                    {"id": "923", "code": "laz"},
                    {"id": "915", "code": "lu-mien"},
                    {"id": "297", "code": "malay"},
                    {"id": "306", "code": "maori"},
                    {"id": "309", "code": "marshallese"},
                    {"id": "336", "code": "nepali"},
                    {"id": "430", "code": "tagalog"},
                    {"id": "54", "code": "tibetan"},
                ],
            },
            {
                "id": "583",
                "code": "middle-eastern",
                "children": [
                    {
                        "id": "52",
                        "code": "arabic",
                        "children": [
                            {"id": "679", "code": "arabic-2"},
                            {"id": "677", "code": "arabic-alphabet"},
                            {"id": "680", "code": "classical-quranic-arabic"},
                            {"id": "681", "code": "egyptian-arabic"},
                            {"id": "682", "code": "gulf-khaliji-arabic"},
                            {"id": "683", "code": "iraqi-arabic"},
                            {"id": "684", "code": "levantine-arabic"},
                            {"id": "678", "code": "modern-standard-arabic-roman-alph"},
                            {"id": "685", "code": "north-african-maghrebi-arabic"},
                        ],
                    },
                    {"id": "21", "code": "hebrew"},
                    {"id": "31", "code": "turkish"},
                    {"id": "388", "code": "aramaic"},
                    {"id": "264", "code": "kurdish"},
                    {"id": "706", "code": "persian"},
                    {"id": "488", "code": "yiddish"},
                ],
            },
            {
                "id": "584",
                "code": "slavic",
                "children": [
                    {"id": "10", "code": "russian"},
                    {"id": "46", "code": "bosnian"},
                    {"id": "16", "code": "croatian"},
                    {"id": "13", "code": "czech"},
                    {"id": "14", "code": "polish"},
                    {"id": "51", "code": "serbian"},
                    {"id": "12", "code": "bulgarian"},
                    {"id": "29", "code": "slovak"},
                    {"id": "30", "code": "slovenian"},
                    {"id": "43", "code": "ukrainian"},
                    {"id": "45", "code": "belarusian"},
                    {"id": "958", "code": "circassian"},
                    {"id": "291", "code": "macedonian"},
                    {"id": "935", "code": "ossetic"},
                    {"id": "959", "code": "other-slavic"},
                ],
            },
            {
                "id": "585",
                "code": "african",
                "children": [
                    {"id": "33", "code": "coptic"},
                    {"id": "41", "code": "swahili"},
                    {"id": "62", "code": "afrikaans"},
                    {"id": "920", "code": "akan-twi"},
                    {"id": "72", "code": "amharic"},
                    {"id": "205", "code": "hausa"},
                    {"id": "916", "code": "kaonde"},
                    {"id": "254", "code": "kinyarwanda"},
                    {"id": "921", "code": "luganda"},
                    {"id": "296", "code": "malagasy"},
                    {"id": "922", "code": "mandinka"},
                    {"id": "934", "code": "nyanja"},
                    {"id": "414", "code": "somali"},
                    {"id": "416", "code": "soninke"},
                    {"id": "483", "code": "wolof"},
                    {"id": "496", "code": "zulu"},
                ],
            },
            {
                "id": "675",
                "code": "native-american",
                "children": [
                    {"id": "48", "code": "cherokee"},
                    {"id": "69", "code": "algonquian-languages"},
                    {"id": "953", "code": "alutiiq"},
                    {"id": "132", "code": "choctaw"},
                    {"id": "925", "code": "citizen-potawatomi"},
                    {"id": "933", "code": "greenlandic"},
                    {"id": "199", "code": "guarani"},
                    {"id": "224", "code": "inuktitut"},
                    {"id": "917", "code": "lakota"},
                    {"id": "328", "code": "nahuatl-languages"},
                    {"id": "961", "code": "other-native-american-languages"},
                    {"id": "378", "code": "quechua"},
                ],
            },
            {
                "id": "615",
                "code": "classics",
                "children": [{"id": "273", "code": "latin"}, {"id": "73", "code": "ancient-greek"}],
            },
            {
                "id": "586",
                "code": "constructed-languages",
                "children": [
                    {"id": "34", "code": "esperanto"},
                    {"id": "222", "code": "interlingua-international-auxiliar"},
                    {"id": "37", "code": "klingon"},
                    {"id": "279", "code": "lojban"},
                    {"id": "722", "code": "morse-code"},
                    {"id": "759", "code": "navi"},
                    {"id": "957", "code": "quenya"},
                ],
            },
            {
                "id": "751",
                "code": "sign-languages",
                "children": [
                    {"id": "940", "code": "american-sign-language-asl"},
                    {"id": "946", "code": "argentinian-sign-language"},
                    {"id": "942", "code": "australian-sign-language-auslan"},
                    {"id": "943", "code": "british-sign-language-bsl"},
                    {"id": "945", "code": "french-sign-language-lsf"},
                    {"id": "944", "code": "korean-sign-language"},
                    {"id": "937", "code": "swedish-sign-language"},
                ],
            },
            {
                "id": "587",
                "code": "other",
                "children": [
                    {"id": "185", "code": "galician"},
                    {"id": "204", "code": "haitian"},
                    {"id": "220", "code": "indo-european-languages"},
                    {"id": "676", "code": "other-language"},
                ],
            },
        ],
    },
    {
        "id": "604",
        "code": "arts-literature",
        "children": [
            {"id": "622", "code": "architecture"},
            {"id": "617", "code": "art"},
            {"id": "623", "code": "design"},
            {"id": "621", "code": "fashion"},
            {"id": "620", "code": "film"},
            {"id": "618", "code": "literature"},
            {"id": "616", "code": "music"},
            {"id": "619", "code": "theatre"},
            {"id": "769", "code": "philosophy"},
        ],
    },
    {
        "id": "605",
        "code": "maths-science",
        "children": [
            {"id": "624", "code": "biology"},
            {"id": "625", "code": "chemistry"},
            {"id": "630", "code": "earth-sciences"},
            {"id": "627", "code": "economics"},
            {"id": "629", "code": "engineering"},
            {"id": "631", "code": "health-sciences"},
            {"id": "628", "code": "maths"},
            {"id": "626", "code": "physics"},
            {"id": "760", "code": "psychology"},
        ],
    },
    {
        "id": "606",
        "code": "the-natural-world",
        "children": [
            {"id": "632", "code": "animals"},
            {"id": "634", "code": "astronomy"},
            {"id": "635", "code": "other-2"},
            {"id": "633", "code": "plants-trees-and-fruits"},
            {"id": "770", "code": "stars"},
        ],
    },
    {
        "id": "607",
        "code": "history-geography",
        "children": [
            {"id": "637", "code": "anthropology"},
            {"id": "638", "code": "capitals"},
            {"id": "642", "code": "civics"},
            {"id": "636", "code": "history"},
            {"id": "639", "code": "maps"},
            {"id": "643", "code": "other-3"},
            {"id": "640", "code": "places"},
            {"id": "641", "code": "religion"},
            {"id": "564", "code": "flags"},
            {"id": "686", "code": "politics"},
        ],
    },
    {
        "id": "608",
        "code": "memory-training",
        "children": [
            {"id": "646", "code": "memory-palaces"},
            {"id": "644", "code": "number-systems"},
            {"id": "645", "code": "playing-card-systems"},
        ],
    },
    {
        "id": "609",
        "code": "professional-and-careers",
        "children": [
            {"id": "649", "code": "business-finance"},
            {"id": "650", "code": "computers-engineering"},
            {"id": "648", "code": "law"},
            {"id": "647", "code": "medicine-healthcare"},
            {"id": "651", "code": "other-4"},
        ],
    },
    {
        "id": "610",
        "code": "standardised-tests",
        "children": [
            {"id": "654", "code": "advanced-placement"},
            {"id": "652", "code": "college-admissions"},
            {"id": "653", "code": "graduate-school"},
            {"id": "656", "code": "other-standardized-tests"},
        ],
    },
    {
        "id": "611",
        "code": "trivia",
        "children": [
            {"id": "660", "code": "art-music-literature"},
            {"id": "659", "code": "geography"},
            {"id": "658", "code": "history-2"},
            {"id": "661", "code": "science-and-nature"},
            {"id": "662", "code": "sports-and-leisure"},
            {"id": "766", "code": "food"},
            {"id": "765", "code": "hobo-symbols"},
            {"id": "763", "code": "miscellaneous"},
            {"id": "762", "code": "people"},
            {"id": "932", "code": "sociology"},
        ],
    },
    {
        "id": "657",
        "code": "entertainment",
        "children": [
            {"id": "761", "code": "board-games"},
            {"id": "511", "code": "pokemon"},
            {"id": "771", "code": "yoga"},
        ],
    },
]

def flatten_tree(categories_tree, categories={}, codes={}, parents=[]):
    for cat in categories_tree:
        catID = cat["id"]

        item = {
            "id": catID,
            "code": cat["code"],
            "children": [x["id"] for x in cat.get("children", [])],
            "parents": parents,
        }
        categories[catID] = item
        codes[cat["code"]] = catID

        if len(item["children"]):
            flatten_tree(cat["children"], categories, codes, [*parents, catID])

    return categories

# ID: {id, code children, parents}
categories = {}

# {CODE: ID}
categories_code = {}

flatten_tree(categories_tree, categories, categories_code)

USER_RANKS = [
    0,
    500,
    1000,
    2000,
    4000,
    8000,
    16000,
    32000,
    64000,
    128000,
    320000,
    800000,
    2000000,
    5000000,
    12500000,
    31250000,
    78125000,
    100000000,
]
