# coding=utf-8
MENU = [
    {"slug": "index", "url": "/"},
    {"slug": "courses", "url": "/community/courses/"},
    {"slug": "login", "url": "/login"},
]

LOCALES = [
    {"slug": "english", "name": "English", "photo": "/static/img/flag_uk.svg"},
    {"slug": "french", "name": "Français", "photo": "/static/img/flag_french.svg"},
]

# https://static.memrise.com/uploads/language_photos/german.png
languages = {
    "afrikaans": {"photo_url": "/static/img/language_photos/Afrikaans.png"},
    "albanian": {"photo_url": "/static/img/language_photos/albanian.png"},
    "american-sign-language-asl": {"photo_url": "/static/img/language_photos/sign-american.png"},
    "ancient-greek": {"photo_url": "/static/img/language_photos/Ancient-Greek.png"},
    "arabic": {"photo_url": "/static/img/language_photos/arabic.png"},
    "armenian": {"photo_url": "/static/img/language_photos/armenian.png"},
    "azerbaijani": {"photo_url": "/static/img/language_photos/azerbaijini.png"},
    "basque": {"photo_url": "/static/img/language_photos/DemoFlags-38_copy.png"},
    "belarusian": {"photo_url": "/static/img/language_photos/belarus.png"},
    "bengali": {"photo_url": "/static/img/language_photos/DemoFlags-61_copy.png"},
    "bosnian": {"photo_url": "/static/img/language_photos/DemoFlags-71_copy.png"},
    "bulgarian": {"photo_url": "/static/img/language_photos/DemoFlags-66_copy.png"},
    "burmese": {"photo_url": "/static/img/language_photos/burmese.png"},
    "cantonese": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "cantonese-jyutping": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "catalan": {"photo_url": "/static/img/language_photos/DemoFlags-29_copy.png"},
    "chinese-simplified": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "chinese-traditional": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "croatian": {"photo_url": "/static/img/language_photos/DemoFlags-30_copy.png"},
    "czech": {"photo_url": "/static/img/language_photos/DemoFlags-19_copy.png"},
    "danish": {"photo_url": "/static/img/language_photos/DemoFlags-25_copy.png"},
    "dutch": {"photo_url": "/static/img/language_photos/Flags_Dutch_copy.png"},
    "english": {"photo_url": "/static/img/language_photos/en.png"},
    "english-us": {"photo_url": "/static/img/language_photos/us_flag.png"},
    "esperanto": {"photo_url": "/static/img/language_photos/DemoFlags-34_copy.png"},
    "estonian": {"photo_url": "/static/img/language_photos/DemoFlags-32_copy.png"},
    "faroese": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Faroese.png"},
    "finnish": {"photo_url": "/static/img/language_photos/DemoFlags-22_copy.png"},
    "flemish": {"photo_url": "/static/img/language_photos/flemish.png"},
    "french": {"photo_url": "/static/img/language_photos/DemoFlags-02_copy.png"},
    "french-sign-language-lsf": {"photo_url": "/static/img/language_photos/sign-french.png"},
    "galician": {"photo_url": "/static/img/language_photos/galician-flag.png"},
    "georgian": {"photo_url": "/static/img/language_photos/georgian.png"},
    "german": {"photo_url": "/static/img/language_photos/german.png"},
    "greek": {"photo_url": "/static/img/language_photos/DemoFlags-26_copy.png"},
    "greenlandic": {"photo_url": "/static/img/language_photos/greenland.png"},
    "hakka": {"photo_url": "/static/img/language_photos/hakka.png"},
    "hebrew": {"photo_url": "/static/img/language_photos/DemoFlags-24_copy.png"},
    "hindi": {"photo_url": "/static/img/language_photos/DemoFlags-28_copy.png"},
    "hungarian": {"photo_url": "/static/img/language_photos/DemoFlags-21_copy.png"},
    "icelandic": {"photo_url": "/static/img/language_photos/DemoFlags-35_copy.png"},
    "indonesian": {"photo_url": "/static/img/language_photos/DemoFlags-64_copy.png"},
    "irish": {"photo_url": "/static/img/language_photos/DemoFlags-12_copy.png"},
    "italian": {"photo_url": "/static/img/language_photos/DemoFlags-06_copy.png"},
    "japanese-4": {"photo_url": "/static/img/language_photos/DemoFlags-09_copy.png"},
    "japanese-no-script": {"photo_url": "/static/img/language_photos/DemoFlags-09_copy.png"},
    "kanji": {"photo_url": "/static/img/language_photos/DemoFlags-09_copy.png"},
    "kazakh": {"photo_url": "/static/img/language_photos/DemoFlags-62_copy.png"},
    "khmer": {"photo_url": "/static/img/language_photos/khmer.png"},
    "korean": {"photo_url": "/static/img/language_photos/korean-flag.png"},
    "kurdish": {"photo_url": "/static/img/language_photos/kurdish-flag1.png"},
    "kyrgyz": {"photo_url": "/static/img/language_photos/kyrgyz.png"},
    "ladin": {"photo_url": "/static/img/language_photos/ladin.png"},
    "latin": {"photo_url": "/static/img/language_photos/latin.png"},
    "latvian": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Latvian.png"},
    "lithuanian": {"photo_url": "/static/img/language_photos/DemoFlags-37_copy.png"},
    "luxembourgish": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Luxembourgish.png"},
    "macedonian": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Macedonian.png"},
    "malay": {"photo_url": "/static/img/language_photos/DemoFlags-60_copy.png"},
    "malayalam": {},
    "maltese": {"photo_url": "/static/img/language_photos/maltese-flag1.png"},
    "mandarin-spoken-only": {"photo_url": "/static/img/language_photos/DemoFlags-01.png"},
    "maori": {"photo_url": "/static/img/language_photos/DemoFlags-55_copy.png"},
    "marathi": {"photo_url": "/static/img/language_photos/DemoFlags-41_copy.png"},
    "mongolian": {"photo_url": "/static/img/language_photos/Flags_BenExtras_Mongolian.png"},
    "nepali": {"photo_url": "/static/img/language_photos/Nepalese.png"},
    "norwegian": {"photo_url": "/static/img/language_photos/DemoFlags-23_copy.png"},
    "occitan": {"photo_url": "/static/img/language_photos/occitan_flag.png"},
    "other-language": {"photo_url": "/static/img/language_photos/other-languages.png"},
    "persian": {"photo_url": "/static/img/language_photos/farsi.png"},
    "polish": {"photo_url": "/static/img/language_photos/DemoFlags-51_copy.png"},
    "portuguese-brazil": {"photo_url": "/static/img/language_photos/pt-br.png"},
    "portuguese-portugal-2": {"photo_url": "/static/img/language_photos/DemoFlags-31_copy.png"},
    "punjabi": {},
    "romanian": {"photo_url": "/static/img/language_photos/Romanian.png"},
    "russian": {"photo_url": "/static/img/language_photos/DemoFlags-20_copy.png"},
    "sanskrit": {"photo_url": "/static/img/language_photos/sanskrit.png"},
    "scots": {"photo_url": "/static/img/language_photos/DemoFlags-36_copy.png"},
    "serbian": {"photo_url": "/static/img/language_photos/DemoFlags-43_copy.png"},
    "slovak": {"photo_url": "/static/img/language_photos/DemoFlags-11_copy.png"},
    "slovenian": {"photo_url": "/static/img/language_photos/DemoFlags-16_copy.png"},
    "somali": {"photo_url": "/static/img/language_photos/somali.png"},
    "spanish-mexico": {"photo_url": "/static/img/language_photos/MEX.png"},
    "spanish-spain": {"photo_url": "/static/img/language_photos/DemoFlags-03_copy.png"},
    "swahili": {"photo_url": "/static/img/language_photos/DemoFlags-45_copy.png"},
    "swedish": {"photo_url": "/static/img/language_photos/DemoFlags-18_copy.png"},
    "tagalog": {"photo_url": "/static/img/language_photos/Tagalog.png"},
    "tamil": {"photo_url": "/static/img/language_photos/tamil-flag.v1.png"},
    "thai": {"photo_url": "/static/img/language_photos/DemoFlags-47_copy.png"},
    "turkish": {"photo_url": "/static/img/language_photos/DemoFlags-13_copy.png"},
    "ukrainian": {"photo_url": "/static/img/language_photos/DemoFlags-49_copy.png"},
    "urdu": {"photo_url": "/static/img/language_photos/urdu.png"},
    "vietnamese": {"photo_url": "/static/img/language_photos/vietnamese.png"},
    "welsh": {"photo_url": "/static/img/language_photos/Flags_Welsh_copy.png"},
    "zulu": {"photo_url": "/static/img/language_photos/Zulu.png"},
}

categories_tree = [
    {
        "id": "569",
        "slug": "languages",
        "children": [
            {
                "id": "578",
                "slug": "european",
                "children": [
                    {"id": "6", "slug": "english"},
                    {"id": "964", "slug": "spanish-mexico"},
                    {"id": "3", "slug": "spanish-spain"},
                    {"id": "2", "slug": "french"},
                    {
                        "id": "879",
                        "slug": "german",
                        "children": [
                            {"id": "4", "slug": "german-2"},
                            {"id": "842", "slug": "small-german-dialects"},
                            {"id": "428", "slug": "swiss-german"},
                        ],
                    },
                    {"id": "688", "slug": "portuguese-brazil"},
                    {"id": "5", "slug": "italian"},
                    {"id": "9", "slug": "portuguese-portugal-2"},
                    {"id": "53", "slug": "dutch"},
                    {"id": "19", "slug": "finnish"},
                    {"id": "17", "slug": "danish"},
                    {"id": "20", "slug": "greek"},
                    {"id": "27", "slug": "norwegian"},
                    {"id": "11", "slug": "swedish"},
                    {"id": "67", "slug": "albanian"},
                    {
                        "id": "79",
                        "slug": "armenian",
                        "children": [
                            {"id": "926", "slug": "eastern-armenian"},
                            {"id": "927", "slug": "western-armenian"},
                        ],
                    },
                    {"id": "32", "slug": "basque"},
                    {"id": "114", "slug": "breton"},
                    {"id": "15", "slug": "catalan"},
                    {"id": "139", "slug": "cornish"},
                    {"id": "963", "slug": "english-us"},
                    {"id": "18", "slug": "estonian"},
                    {"id": "173", "slug": "faroese"},
                    {"id": "767", "slug": "flemish"},
                    {"id": "190", "slug": "georgian"},
                    {"id": "950", "slug": "gothic-2"},
                    {"id": "23", "slug": "hungarian"},
                    {"id": "24", "slug": "icelandic"},
                    {"id": "26", "slug": "irish"},
                    {"id": "268", "slug": "ladin"},
                    {"id": "269", "slug": "ladino"},
                    {"id": "274", "slug": "latvian"},
                    {"id": "35", "slug": "lithuanian"},
                    {"id": "290", "slug": "luxembourgish"},
                    {"id": "299", "slug": "maltese"},
                    {"id": "305", "slug": "manx"},
                    {"id": "353", "slug": "occitan"},
                    {"id": "383", "slug": "romanian"},
                    {
                        "id": "389",
                        "children": [
                            {"id": "286", "slug": "lule-sami"},
                            {"id": "346", "slug": "northern-sami"},
                            {"id": "421", "slug": "southern-sami"},
                            {"id": "918", "slug": "ume-sami"},
                        ],
                        "slug": "sami-languages",
                    },
                    {"id": "39", "slug": "scots"},
                    {"id": "183", "slug": "scottish-gaelic"},
                    {"id": "40", "slug": "welsh"},
                ],
            },
            {
                "id": "612",
                "slug": "chinese",
                "children": [
                    {"id": "547", "slug": "chinese-simplified"},
                    {"id": "550", "slug": "chinese-traditional"},
                    {"id": "549", "slug": "mandarin-spoken-only"},
                    {"id": "548", "slug": "cantonese"},
                    {"id": "553", "slug": "cantonese-jyutping"},
                    {"id": "552", "slug": "ningbo-dialect"},
                    {"id": "551", "slug": "taishanese"},
                    {"id": "919", "slug": "hakka"},
                ],
            },
            {
                "id": "613",
                "slug": "japanese",
                "children": [
                    {"id": "665", "slug": "japanese-4"},
                    {"id": "666", "slug": "kanji"},
                    {"id": "668", "slug": "japanese-no-script"},
                ],
            },
            {
                "id": "582",
                "slug": "indian",
                "children": [
                    {"id": "103", "slug": "bengali"},
                    {"id": "201", "slug": "gujarati"},
                    {"id": "22", "slug": "hindi"},
                    {"id": "438", "slug": "telugu"},
                    {"id": "470", "slug": "urdu"},
                    {"id": "36", "slug": "marathi"},
                    {"id": "240", "slug": "kannada"},
                    {"id": "298", "slug": "malayalam"},
                    {"id": "363", "slug": "pali"},
                    {"id": "376", "slug": "punjabi"},
                    {"id": "393", "slug": "sanskrit"},
                    {"id": "434", "slug": "tamang"},
                    {"id": "436", "slug": "tamil"},
                ],
            },
            {
                "id": "614",
                "slug": "asian-and-pacific",
                "children": [
                    {"id": "25", "slug": "indonesian"},
                    {"id": "8", "slug": "korean"},
                    {"id": "441", "slug": "thai"},
                    {"id": "474", "slug": "vietnamese"},
                    {"id": "322", "slug": "mongolian"},
                    {"id": "42", "slug": "azerbaijani"},
                    {"id": "49", "slug": "hawaiian"},
                    {"id": "50", "slug": "kazakh"},
                    {"id": "64", "slug": "ainu"},
                    {"id": "965", "slug": "australian"},
                    {"id": "117", "slug": "burmese"},
                    {"id": "119", "slug": "cebuano"},
                    {"id": "954", "slug": "dzongkha-2"},
                    {"id": "955", "slug": "javanese-2"},
                    {"id": "245", "slug": "karen-languages"},
                    {"id": "122", "slug": "khmer"},
                    {"id": "267", "slug": "kyrgyz"},
                    {"id": "923", "slug": "laz"},
                    {"id": "915", "slug": "lu-mien"},
                    {"id": "297", "slug": "malay"},
                    {"id": "306", "slug": "maori"},
                    {"id": "309", "slug": "marshallese"},
                    {"id": "336", "slug": "nepali"},
                    {"id": "430", "slug": "tagalog"},
                    {"id": "54", "slug": "tibetan"},
                ],
            },
            {
                "id": "583",
                "slug": "middle-eastern",
                "children": [
                    {
                        "id": "52",
                        "slug": "arabic",
                        "children": [
                            {"id": "679", "slug": "arabic-2"},
                            {"id": "677", "slug": "arabic-alphabet"},
                            {"id": "680", "slug": "classical-quranic-arabic"},
                            {"id": "681", "slug": "egyptian-arabic"},
                            {"id": "682", "slug": "gulf-khaliji-arabic"},
                            {"id": "683", "slug": "iraqi-arabic"},
                            {"id": "684", "slug": "levantine-arabic"},
                            {"id": "678", "slug": "modern-standard-arabic-roman-alph"},
                            {"id": "685", "slug": "north-african-maghrebi-arabic"},
                        ],
                    },
                    {"id": "21", "slug": "hebrew"},
                    {"id": "31", "slug": "turkish"},
                    {"id": "388", "slug": "aramaic"},
                    {"id": "264", "slug": "kurdish"},
                    {"id": "706", "slug": "persian"},
                    {"id": "488", "slug": "yiddish"},
                ],
            },
            {
                "id": "584",
                "slug": "slavic",
                "children": [
                    {"id": "10", "slug": "russian"},
                    {"id": "46", "slug": "bosnian"},
                    {"id": "16", "slug": "croatian"},
                    {"id": "13", "slug": "czech"},
                    {"id": "14", "slug": "polish"},
                    {"id": "51", "slug": "serbian"},
                    {"id": "12", "slug": "bulgarian"},
                    {"id": "29", "slug": "slovak"},
                    {"id": "30", "slug": "slovenian"},
                    {"id": "43", "slug": "ukrainian"},
                    {"id": "45", "slug": "belarusian"},
                    {"id": "958", "slug": "circassian"},
                    {"id": "291", "slug": "macedonian"},
                    {"id": "935", "slug": "ossetic"},
                    {"id": "959", "slug": "other-slavic"},
                ],
            },
            {
                "id": "585",
                "slug": "african",
                "children": [
                    {"id": "33", "slug": "coptic"},
                    {"id": "41", "slug": "swahili"},
                    {"id": "62", "slug": "afrikaans"},
                    {"id": "920", "slug": "akan-twi"},
                    {"id": "72", "slug": "amharic"},
                    {"id": "205", "slug": "hausa"},
                    {"id": "916", "slug": "kaonde"},
                    {"id": "254", "slug": "kinyarwanda"},
                    {"id": "921", "slug": "luganda"},
                    {"id": "296", "slug": "malagasy"},
                    {"id": "922", "slug": "mandinka"},
                    {"id": "934", "slug": "nyanja"},
                    {"id": "414", "slug": "somali"},
                    {"id": "416", "slug": "soninke"},
                    {"id": "483", "slug": "wolof"},
                    {"id": "496", "slug": "zulu"},
                ],
            },
            {
                "id": "675",
                "slug": "native-american",
                "children": [
                    {"id": "48", "slug": "cherokee"},
                    {"id": "69", "slug": "algonquian-languages"},
                    {"id": "953", "slug": "alutiiq"},
                    {"id": "132", "slug": "choctaw"},
                    {"id": "925", "slug": "citizen-potawatomi"},
                    {"id": "933", "slug": "greenlandic"},
                    {"id": "199", "slug": "guarani"},
                    {"id": "224", "slug": "inuktitut"},
                    {"id": "917", "slug": "lakota"},
                    {"id": "328", "slug": "nahuatl-languages"},
                    {"id": "961", "slug": "other-native-american-languages"},
                    {"id": "378", "slug": "quechua"},
                ],
            },
            {
                "id": "615",
                "slug": "classics",
                "children": [
                    {"id": "273", "slug": "latin"},
                    {"id": "73", "slug": "ancient-greek"},
                ],
            },
            {
                "id": "586",
                "slug": "constructed-languages",
                "children": [
                    {"id": "34", "slug": "esperanto"},
                    {"id": "222", "slug": "interlingua-international-auxiliar"},
                    {"id": "37", "slug": "klingon"},
                    {"id": "279", "slug": "lojban"},
                    {"id": "722", "slug": "morse-code"},
                    {"id": "759", "slug": "navi"},
                    {"id": "957", "slug": "quenya"},
                ],
            },
            {
                "id": "751",
                "slug": "sign-languages",
                "children": [
                    {"id": "940", "slug": "american-sign-language-asl"},
                    {"id": "946", "slug": "argentinian-sign-language"},
                    {"id": "942", "slug": "australian-sign-language-auslan"},
                    {"id": "943", "slug": "british-sign-language-bsl"},
                    {"id": "945", "slug": "french-sign-language-lsf"},
                    {"id": "944", "slug": "korean-sign-language"},
                    {"id": "937", "slug": "swedish-sign-language"},
                ],
            },
            {
                "id": "587",
                "slug": "other",
                "children": [
                    {"id": "185", "slug": "galician"},
                    {"id": "204", "slug": "haitian"},
                    {"id": "220", "slug": "indo-european-languages"},
                    {"id": "676", "slug": "other-language"},
                ],
            },
        ],
    },
    {
        "id": "604",
        "slug": "arts-literature",
        "children": [
            {"id": "622", "slug": "architecture"},
            {"id": "617", "slug": "art"},
            {"id": "623", "slug": "design"},
            {"id": "621", "slug": "fashion"},
            {"id": "620", "slug": "film"},
            {"id": "618", "slug": "literature"},
            {"id": "616", "slug": "music"},
            {"id": "619", "slug": "theatre"},
            {"id": "769", "slug": "philosophy"},
        ],
    },
    {
        "id": "605",
        "slug": "maths-science",
        "children": [
            {"id": "624", "slug": "biology"},
            {"id": "625", "slug": "chemistry"},
            {"id": "630", "slug": "earth-sciences"},
            {"id": "627", "slug": "economics"},
            {"id": "629", "slug": "engineering"},
            {"id": "631", "slug": "health-sciences"},
            {"id": "628", "slug": "maths"},
            {"id": "626", "slug": "physics"},
            {"id": "760", "slug": "psychology"},
        ],
    },
    {
        "id": "606",
        "slug": "the-natural-world",
        "children": [
            {"id": "632", "slug": "animals"},
            {"id": "634", "slug": "astronomy"},
            {"id": "635", "slug": "other-2"},
            {"id": "633", "slug": "plants-trees-and-fruits"},
            {"id": "770", "slug": "stars"},
        ],
    },
    {
        "id": "607",
        "slug": "history-geography",
        "children": [
            {"id": "637", "slug": "anthropology"},
            {"id": "638", "slug": "capitals"},
            {"id": "642", "slug": "civics"},
            {"id": "636", "slug": "history"},
            {"id": "639", "slug": "maps"},
            {"id": "643", "slug": "other-3"},
            {"id": "640", "slug": "places"},
            {"id": "641", "slug": "religion"},
            {"id": "564", "slug": "flags"},
            {"id": "686", "slug": "politics"},
        ],
    },
    {
        "id": "608",
        "slug": "memory-training",
        "children": [
            {"id": "646", "slug": "memory-palaces"},
            {"id": "644", "slug": "number-systems"},
            {"id": "645", "slug": "playing-card-systems"},
        ],
    },
    {
        "id": "609",
        "slug": "professional-and-careers",
        "children": [
            {"id": "649", "slug": "business-finance"},
            {"id": "650", "slug": "computers-engineering"},
            {"id": "648", "slug": "law"},
            {"id": "647", "slug": "medicine-healthcare"},
            {"id": "651", "slug": "other-4"},
        ],
    },
    {
        "id": "610",
        "slug": "standardised-tests",
        "children": [
            {"id": "654", "slug": "advanced-placement"},
            {"id": "652", "slug": "college-admissions"},
            {"id": "653", "slug": "graduate-school"},
            {"id": "656", "slug": "other-standardized-tests"},
        ],
    },
    {
        "id": "611",
        "slug": "trivia",
        "children": [
            {"id": "660", "slug": "art-music-literature"},
            {"id": "659", "slug": "geography"},
            {"id": "658", "slug": "history-2"},
            {"id": "661", "slug": "science-and-nature"},
            {"id": "662", "slug": "sports-and-leisure"},
            {"id": "766", "slug": "food"},
            {"id": "765", "slug": "hobo-symbols"},
            {"id": "763", "slug": "miscellaneous"},
            {"id": "762", "slug": "people"},
            {"id": "932", "slug": "sociology"},
        ],
    },
    {
        "id": "657",
        "slug": "entertainment",
        "children": [
            {"id": "761", "slug": "board-games"},
            {"id": "511", "slug": "pokemon"},
            {"id": "771", "slug": "yoga"},
        ],
    },
]

def flatten_tree(categories_tree, categories={}, slugs={}, parents=[]):
    for cat in categories_tree:
        catID = cat["id"]

        item = {
            "id": catID,
            "slug": cat["slug"],
            "children": [x["id"] for x in cat.get("children", [])],
            "parents": parents,
        }
        categories[catID] = item
        slugs[cat["slug"]] = catID

        if len(item["children"]):
            flatten_tree(cat["children"], categories, slugs, [*parents, catID])

    return categories

# ID: {id, slug, children, parents}
categories = {}

# {SLUG: ID}
categories_slug = {}

flatten_tree(categories_tree, categories, categories_slug)

USER_RANKS = [
    0,
    500,
    1000,
    2000,
    4000,
    8000,
    16000,
    32000,
    64000,
    128000,
    320000,
    800000,
    2000000,
    5000000,
    12500000,
    31250000,
    78125000,
    100000000,
]
